### ISSUE TITLE
how do i build it?

### ISSUE THREAD

**Issue by tman10001** [evaan/FrostBurn#14]
i tried using the regular cmd way but it didnt work

**Comment by evaan** [comment]
"it didnt work" doesn't provide much info, can you please specify?

**Comment by tman10001** [comment]
I was able to build it but the jars had errors

**Comment by tman10001** [comment]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'frostburn'!
Exit Code: -1

i got this when i ran frostburn 1.0 dev and 1.0 jar

**Comment by evaan** [comment]
I found the issue, currently working on fixing it.

**Comment by evaan** [comment]
Fixed
