### ISSUE TITLE
runite

### ISSUE THREAD

**Issue by zopac** [evaan/FrostBurn#25]
i am going to leave an issue every single day until you start working on runite again

**Comment by evaan** [comment]
![image](https://user-images.githubusercontent.com/41494790/118877400-fa76ed00-b8c8-11eb-825b-591cd56f02b8.png)

**Comment by notyoursleep** [comment]
lol evaan work more or frostburn is not strong :^p

**Comment by notyoursleep** [comment]
or work harder however im russian so i don't give a fuck :D
