### ISSUE TITLE
[Bug] Crashed when Enabling NoFall

### ISSUE THREAD

**Issue by Metacinnabar** [evaan/FrostBurn#28]
### Description
Game crashed when I enabled NoFall, but I am unsure if NoFall is correlated to the crash. The mods I have is present in the logs and I'm using the latest release from the releases page on Github.
Edit:
Crashed again with the same error when enabling Scaffold.
### Logs
[latest.log](https://paste.mod.gg/ramewelaku.sql)

**Comment by evaan** [comment]
Just made a new release can you try that and let me know how it works?

**Comment by Metacinnabar** [comment]
Works! Thanks!

**Comment by Metacinnabar** [comment]
Crashed again seemingly with the same error when using Nuker.
[latest.log](https://paste.mod.gg/jagomiziri.pl)

**Comment by evaan** [comment]
https://file.io/dahBZzqfvvIf here try this

**Comment by Metacinnabar** [comment]
![image](https://user-images.githubusercontent.com/45357714/123565985-ea282b00-d801-11eb-844d-b6b8e0532e5f.png)

**Comment by evaan** [comment]
uhhh lemme upload it somewhere else

**Comment by evaan** [comment]
https://www.mediafire.com/file/bvds2mt6rbeunu7/frostburn-1.0.jar/file

**Comment by Metacinnabar** [comment]
Looks good, haven't crashed since.
